### PR TITLE
filters

### LINKED ISSUE #3: Screen rotation
When recording from a screen which is configured with rotation, the screen recording is not rotated.

### LINKED ISSUE #20: set recording frame rate
It would be nice to be able to set the recording frame rate. In my particular use case, my system is too slow to handle a 60fps recording without seriously slowing down everything else. Is there an easy way to add this? or even hardcode it?

### LINKED ISSUE #38: My experiments with FFMpeg filters
I am working on a ffmpeg-based encoder for another project and I used wf-recorder to experiment with ffmpeg filters. The result can be found in https://github.com/schauveau/wf-recorder-x  
This is actually working quite well. The filters are providing a lot of nice features (overlay logo or text, change fps, scaling, adjust brightness, contrast, saturation, ...).

### LINKED ISSUE #77: Allow downscaling resolution of video recording
When I record my 4k screen to `video4linux2`, wf-recorder uses 100% CPU. I want to record full screen, but I'm willing to sacrifice resolution, and record it in Full HD, if that helps reducing CPU usage. If I record a part of the screen of 1920x1200 resolution, wf-recorder only consumes ~25% CPU. I'd like to be able to tell wf-recorder to record full screen but downscale it to Full HD, so that hopefully CPU usage is not that high.

### LINKED ISSUE #87: Put OpenCL dependency behind a conditional
in `meson.build`, you currently have the following:
```meson
opencl = dependency('OpenCL', required : get_option('opencl'))
```

It should be written like so:
```meson
if not get_option('opencl').disabled()
  opencl = dependency('OpenCL', required : true)
else
  opencl = disabler()
endif
```

This way it is possible to build a package that doesn't depends on OpenCL on a build-machine which has it. No pull request done because without #66 being fixed I can't test it on my machine.

### PR DESCRIPTION
**Pull request by ammen99**
In this PR, I have tried to port the work on ffmpeg filters from [this fork](https://github.com/schauveau/wf-recorder-x).
Many thanks to @schauveau for doing the initial work on this! The forked repo also contains a lot of useful tips, take a look if you don't know what filters are useful.

There were many changes in that fork. So far, I have picked only those that enable filters to work in wf-recorder. To my surprise, this resulted in a big simplification where the frame handling is done, because now we can just use a filter to upload data in the case of VAAPI codec. Since we can also convert data on the GPU with `scale_vaapi`, I think that OpenCL support is no longer necessary.

All in all, this is a pretty big change, so it would be good if more people can test before we merge this. A 0.3 release will probably make sense afterwards.

Fixes #3 (you can rotate with a filter)
Fixes #20 (you can limit framerate with `-F fps=30` or `-D -F framestep=2`)
Fixes #38
Fixes #77 (`scale`/`scale_vaapi` filter)
Fixes #87 (because opencl is not a dependency anymore)

Happy new year everyone!

### CODE REVIEW

**Comment by b12f** [comment]
Can't wait for this to drop! Tell me if you need testing done or help with anything other than c++ coding ;)

**Comment by ammen99** [comment]
> Can't wait for this to drop! Tell me if you need testing done or help with anything other than c++ coding ;)

This PR is waiting for testing ;) Otherwise, there's nothing else to do.

**Comment by maximbaz** [comment]
Nice work @ammen99, I am happy to test!

With v4l2loopback I sadly don't notice any performance improvements, in fact with downscale filter applied to record in FullHD instead of 4k the idle CPU usage is increased from 6% to 9%, and when I play the stream in `mpv` in both cases CPU usage goes to 100%. If on the other hand I select 1/4th of the screen with `-g` and don't apply any scale filters, CPU usage will be 2% in idle and 25% when is playing in mpv.

```
$ ./wf-recorder-filters --muxer=v4l2 --codec=rawvideo --pixel-format=yuv420p -F 'scale=w=1920:h=1200' --file=/dev/video9
```

With vaapi, sadly I can't even get it to work in this branch 😞 

When running from `master`, this works:

```
$ ./wf-recorder-master -f test-vaapi.mkv -c h264_vaapi -d /dev/dri/renderD128
selected region 0 0 0 0
[h264_vaapi @ 0x7fcaac001d00] No quality level set; using default (20).
Output #0, matroska, to 'test-vaapi.mkv':
    Stream #0:0: Unknown: none (h264_vaapi)
[matroska @ 0x7fcaac000d40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
^C[matroska @ 0x7fcaac000d40] pts (0) < dts (1570) in stream 0
```

When running from `filters` branch, it crashes:

```
$ ./wf-recorder-filters -f test-vaapi.mkv -c h264_vaapi -d /dev/dri/renderD128
selected region 0 0 0 0
[Source @ 0x7f4ec404e100] sws_param option is deprecated and ignored
Using video filter: hwupload,scale_vaapi=format=nv12
[h264_vaapi @ 0x7f4ec4001bc0] No quality level set; using default (20).
[h264_vaapi @ 0x7f4ec4001bc0] colour_primaries does not match inferred value: 0, but should be 2.
[h264_vaapi @ 0x7f4ec4001bc0] Failed to write unit 0 (type 7).
[h264_vaapi @ 0x7f4ec4001bc0] Failed to write packed header.
[h264_vaapi @ 0x7f4ec4001bc0] Failed to write sequence header for extradata: -1094995529.
avcodec_open2 failed: Invalid data found when processing input
```

I can see it applied some filters by default, but I can't find a value that will not make it crash, for example I tried this value that I found somewhere, which is supposed to scale, but it still crashes:


```
$ ./wf-recorder-filters -f test-vaapi.mkv -c h264_vaapi -d /dev/dri/renderD128 -F 'format=nv12,hwupload,scale_vaapi=w=1920:h=1200'
Output file "test-vaapi.mkv" exists. Overwrite? Y/n: y
selected region 0 0 0 0
[Source @ 0x7fb2bc04e180] sws_param option is deprecated and ignored
Using video filter: format=nv12,hwupload,scale_vaapi=w=1920:h=1200
[h264_vaapi @ 0x7fb2bc001c40] No quality level set; using default (20).
[h264_vaapi @ 0x7fb2bc001c40] colour_primaries does not match inferred value: 0, but should be 2.
[h264_vaapi @ 0x7fb2bc001c40] Failed to write unit 0 (type 7).
[h264_vaapi @ 0x7fb2bc001c40] Failed to write packed header.
[h264_vaapi @ 0x7fb2bc001c40] Failed to write sequence header for extradata: -1094995529.
avcodec_open2 failed: Invalid data found when processing input
```

Using `--force-yuv` doesn't help because I see it complains that it is not supported by my hardware:

```
$ ./wf-recorder-filters -f test-vaapi.mkv -c h264_vaapi -d /dev/dri/renderD128 -F 'format=nv12,hwupload,scale_vaapi=w=1920:h=1200' --force-yuv
Output file "test-vaapi.mkv" exists. Overwrite? Y/n: y
selected region 0 0 0 0
[Source @ 0x7f6ed004e180] sws_param option is deprecated and ignored
Ignoring request to force yuv420p, because it is not supported by the codec
Using video filter: format=nv12,hwupload,scale_vaapi=w=1920:h=1200
[h264_vaapi @ 0x7f6ed0001c40] No quality level set; using default (20).
[h264_vaapi @ 0x7f6ed0001c40] colour_primaries does not match inferred value: 0, but should be 2.
[h264_vaapi @ 0x7f6ed0001c40] Failed to write unit 0 (type 7).
[h264_vaapi @ 0x7f6ed0001c40] Failed to write packed header.
[h264_vaapi @ 0x7f6ed0001c40] Failed to write sequence header for extradata: -1094995529.
avcodec_open2 failed: Invalid data found when processing input
```

If you have some ideas, I would be happy to try some more 🙂

**Comment by ammen99** [comment]
@maximbaz Thank you for testing! I have been busy these last few months and couldn't look into your issue. I just tried your commands though and they seem to work here. I wonder what is different. Could you try running with `-l`, maybe it will give us some more information.

**Comment by ammen99** [comment]
> With v4l2loopback I sadly don't notice any performance improvements, in fact with downscale filter applied to record in FullHD instead of 4k the idle CPU usage is increased from 6% to 9%, and when I play the stream in `mpv` in both cases CPU usage goes to 100%. If on the other hand I select 1/4th of the screen with `-g` and don't apply any scale filters, CPU usage will be 2% in idle and 25% when is playing in mpv.

This is likely because wf-recorder still receives the full resolution buffer, which is given over to ffmpeg and first after that the scaling happens. Unfortunately, we cannot request a scaled down buffer from the compositor.

So depending on how expensive encoding it, lowering the resolution in this way might indeed result in higher CPU usage.

**Comment by ammen99** [comment]
> wf-recorder --muxer=v4l2 --codec=mjpeg --file=/dev/video8

Curious, I just tried the same command on my machine and it works .. Any errors from ffmpeg? Can you try running wf-recorder with `-l` for a bit more debugging information from ffmpeg?

**Comment by ammen99** [comment]
Has anybody tested with extended logging enabled? @maximbaz @L-as @b12f

**Comment by mstoeckl** [comment]
> Has anybody tested with extended logging enabled?

I have, but commands like `wf-recorder -f test-vaapi.mkv -c h264_vaapi -d /dev/dri/renderD128 -F 'format=nv12,hwupload,scale_vaapi=w=1920:h=1200'` and `wf-recorder --muxer=v4l2 --codec=mjpeg --file=/dev/video8` both work fine when I run them with this branch, so I don't think the logs would reveal anything new.

> This PR is waiting for testing ;) Otherwise, there's nothing else to do.

I've looked over the commits for this PR, and except for two problems, everything looks good to me:
* Setting `"sws_param=flags=fast_bilinear"` has been deprecated and does not do anything (except for printing "sws_param option is deprecated and ignored".)
* The recorded videos have too low contrast; I suspect the auto_scaler produces limited (mpeg) range YUV data instead of full (jpeg) range, which the video encoder expects due to `videoCodecCtx->color_range = AVCOL_RANGE_JPEG;`. There's probably a control to change the behavior of the rgb-yuv scaling, but I don't yet know where it is.

**Comment by ammen99** [comment]
> > Has anybody tested with extended logging enabled?
> 
> I have, but commands like `wf-recorder -f test-vaapi.mkv -c h264_vaapi -d /dev/dri/renderD128 -F 'format=nv12,hwupload,scale_vaapi=w=1920:h=1200'` and `wf-recorder --muxer=v4l2 --codec=mjpeg --file=/dev/video8` both work fine when I run them with this branch.
> 
> > This PR is waiting for testing ;) Otherwise, there's nothing else to do.
> 
> I've looked over the commits for this PR, and except for two problems, everything looks good to me:
> 
> * Setting `"sws_param=flags=fast_bilinear"` has been deprecated and does not do anything (except for printing "sws_param option is deprecated and ignored".)
> * The recorded videos have too low contrast; I suspect the auto_scaler produces limited (mpeg) range YUV data instead of full (jpeg) range, which the video encoder expects due to `videoCodecCtx->color_range = AVCOL_RANGE_JPEG;`.
> 
> A possible fix for both issues
> ```diff
> diff --git a/src/frame-writer.cpp b/src/frame-writer.cpp
> index 97c77ad..043d772 100644
> --- a/src/frame-writer.cpp
> +++ b/src/frame-writer.cpp
> @@ -128,6 +128,7 @@ void FrameWriter::init_video_filters(AVCodec *codec)
>      }
>  
>      this->videoFilterGraph = avfilter_graph_alloc();
> +    av_opt_set(videoFilterGraph, "scale_sws_opts", "flags=fast_bilinear:src_range=1:dst_range=1", 0);
>  
>      const AVFilter* source = avfilter_get_by_name("buffer");
>      const AVFilter* sink   = avfilter_get_by_name("buffersink");
> @@ -145,7 +146,6 @@ void FrameWriter::init_video_filters(AVCodec *codec)
>      buffer_filter_config << ":pix_fmt=" << (int)this->get_input_format();
>      buffer_filter_config << ":time_base=" << US_RATIONAL.num << "/" << US_RATIONAL.den;
>      buffer_filter_config << ":pixel_aspect=1/1";
> -    buffer_filter_config << ":sws_param=flags=fast_bilinear";
>  
>      int err = avfilter_graph_create_filter(&this->videoFilterSourceCtx, source,
>          "Source", buffer_filter_config.str().c_str(), NULL, this->videoFilterGraph);
> ```

Thank you for the detailed testing & bug fixing! I have pushed your fix to this branch. I guess we can merge this, make a release in a few days and then wait for the bug reports, if there are any :)

**Pull request merged**
