### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by fwSmit**
The geometry format wasn't mentioned anywhere, so I had some trouble finding the right format. This documentation is to make it a little easier for other users

### CODE REVIEW

**Review by ammen99 — COMMENTED** [review]
Thanks, LGTM! Would you mind adding the format clarification to the help message in main.cpp?

**Comment by fwSmit** [comment]
> Thanks, LGTM! Would you mind adding the format clarification to the help message in main.cpp?

Yes, I added it to the first commit :+1:

**Comment by fwSmit** [comment]
Ping

**Comment by ammen99** [comment]
> Ping
LGTM now, thanks :)

**Pull request merged**
