### PR TITLE
Implement VAAPI and custom parameters support

### LINKED ISSUE #9: Specify codec options from command line
#7 allows to specify codec from command line. But user still has no ability to specify codec options. Currently, for `libx264` these parameters are set: crf 20, tune zerolatency, preset ultrafast. For any other codec default parameters from `libavcodec` are being supplied.

I think the best is to include a list of predefined codecs (I have specified them [here](https://github.com/ammen99/wf-recorder/issues/2#issuecomment-472830274)) and provide an interface for users to adjust codec options for their needs. That's of course not a complete list, but these codecs are first to come up in my mind.

### PR DESCRIPTION
**Pull request by ammen99**
Fixes #9 and #8 

@hedgepigdaniel @foxpy Can you check if this works for you? See the updated README for instructions how to use VAAPI and custom options.

### CODE REVIEW

**Comment by hedgepigdaniel** [comment]
hmm not quite: "No usable encoding profile found."

```shell
$ build/wf-recorder -o eDP-1 -c h264_vaapi -d /dev/dri/renderD128 
selected region 0 0 0 0
[h264_vaapi @ 0x7fbcd8001b80] No usable encoding profile found.
Output #0, mp4, to 'recording.mp4':
    Stream #0:0: Unknown: none
[mp4 @ 0x7fbcd8000d00] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Segmentation fault (core dumped)
```

```
#1  0x00005568cf731677 in FrameWriter::add_frame (this=0x7fbcd8000b40, 
    pixels=0x7fbcdce1a000 "wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377wU(\377"..., msec=0, y_invert=true)
    at ../src/frame-writer.cpp:237
        stride = {-15360}
        formatted_pixels = 0x7fbcdedba400 "\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\231xL\377\062\062\062\377\062\062\062\377\062\062\062\377\062\062\062\377\062\062\062\377\062\062\062\377\062\062\062\377\062\062\062\377\062\062\062\377"...
        output_frame = 0x7fbcd8000c80
        got_output = 0
#2  0x00005568cf7354d7 in write_loop (params=...) at ../src/main.cpp:305
        buffer = @0x5568cf742740: {wl_buffer = 0x5568d1393590, data = 0x7fbcdce1a000, format = WL_SHM_FORMAT_ARGB8888, width = 3840, height = 2160, stride = 15360, y_invert = true, presented = {tv_sec = 32725, 
            tv_nsec = 165984748}, base_msec = 0, released = {_M_base = {static _S_alignment = 1, _M_i = false}}, available = {_M_base = {static _S_alignment = 1, _M_i = true}}}
        sigset = {__val = {2, 0 <repeats 15 times>}}
        writer = std::unique_ptr<FrameWriter> = {get() = 0x7fbcd8000b40}
        last_encoded_frame = 0
#3  0x00005568cf73594c in <lambda()>::operator()(void) const (__closure=0x5568d1393b88) at ../src/main.cpp:616
        params = {file = "recording.mp4", width = 0, height = 0, format = INPUT_FORMAT_BGR0, codec = "h264_vaapi", hw_device = "/dev/dri/renderD128", codec_options = std::map with 0 elements}
```

**Comment by ammen99** [comment]
The crash is most likely because the encoder fails to initialize ...

**Comment by ammen99** [comment]
@hedgepigdaniel Can you try changing formats https://github.com/ammen99/wf-recorder/pull/10/files#diff-790e5e488ac06652348360de86af0cdeR110 to `VAAPI_VLD` or the others available?

Also I wonder whether it is possible that not all hardware accepts RGB data? I hardcoded it here: https://github.com/ammen99/wf-recorder/pull/10/files#diff-790e5e488ac06652348360de86af0cdeR59

If this should change, then we'll need to `sws_scale` here as well, the problem is, I don't know which format it will want to have. I'll try with YUV as well.

**Comment by foxpy** [comment]
> Can you check if this works for you?

```
~/wf-recorder (pullrequest|…) [255] $ build/wf-recorder -f test-vaapi.mkv -c h264_vaapi -d /dev/dri/renderD128 -g (slurp)
Adjusted geometry: 315,232 846x278
selected region 315 232 846 278
[h264_vaapi @ 0x7fce84002000] No usable encoding profile found.
Output #0, matroska, to 'test-vaapi.mkv':
    Stream #0:0: Unknown: none
[matroska @ 0x7fce84000d00] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Failed to write file header
```

**Comment by foxpy** [comment]
> I don't know which format it will want to have.

I use `nv12` for my Intel GPU.

```bash
ffmpeg -hide_banner -loglevel verbose -vaapi_device /dev/dri/renderD128 -f x11grab -video_size 1366x768 -framerate 60 -i $DISPLAY -vf 'hwupload,scale_vaapi=format=nv12' -c:v h264_vaapi -qp 24 output.mp4
```

**Comment by hedgepigdaniel** [comment]
@foxpy that makes me think that in the long term what we really need is a capture "device" for ffmpeg, along the lines of x11grab. That would provide full flexibility in terms of codecs, hardware acceleration, etc.

**Comment by hedgepigdaniel** [comment]
It works with the change here: https://github.com/ammen99/wf-recorder/pull/11 :smiley:

**Comment by ammen99** [comment]
@hedgepigdaniel Thanks for the tip.
@foxpy please test the nv12 patch, if it works for you as well we can merge it.

**Comment by foxpy** [comment]
> please test the nv12 patch, if it works for you as well we can merge it.

Just have tested, works flawlessly. :D

**Comment by foxpy** [comment]
@hedgepigdaniel is absolutely right, the best solution is to implement waygrab device in ffmpeg so already existing screen recorders may work in any Wayland composer with a bit of patching.

**Comment by ammen99** [comment]
@foxpy I disagree. To me, wf-recorder is easier to use than ffmpeg (though not as flexible)

**Comment by foxpy** [comment]
wf-recorder could just use Wayland grab ffmpeg interface like people do with x11grab in X11 screen recorders.

**Comment by ammen99** [comment]
Yes, but we still have the problem that such an interface is not implemented. Anyway merging as it now works.

**Pull request merged**
