### PR TITLE
Make default codec configurable

### PR DESCRIPTION
**Pull request by soreau**

### CODE REVIEW

**Comment by MichaelAquilina** [comment]
Works for me :)

**Comment by MichaelAquilina** [comment]
Maybe update the README to reflect this change?

**Comment by MichaelAquilina** [comment]
Actually hold up - just realised the machine I was testing this on had a copy of x264 installed! Will find a clean environment to test it on first

**Comment by ammen99** [comment]
Thanks @soreau for writing and @MichaelAquilina for testing!

**Pull request merged**
