### PR TITLE
Support writing to video loopback: Libavdevice and set muxer

### PR DESCRIPTION
**Pull request by RX14**
Resend of #43.

### CODE REVIEW

**Comment by ammen99** [comment]
WFM. @soreau, does this break anything for you?

**Comment by soreau** [comment]
> WFM. @soreau, does this break anything for you?

@ammen99 Seems good to me.

**Comment by ammen99** [comment]
Thanks for rebasing this!

**Comment by NilsIrl** [comment]
If I understand correctly this could be used with OBS to stream your wayland desktop?

How is this possible?

**Comment by soreau** [comment]
If I understand correctly, this basically allows the desktop to be streamed to a node such as /dev/video2 which should allow the stream to be used as a video input device.

**Comment by NilsIrl** [comment]
I tried what's in the README and got the following error:

```
selected region 0 0 0 0
Choosing pixel format bgr0
Output #0, v4l2, to '/dev/video2':
    Stream #0:0: Unknown: none (rawvideo)
avio_open failed
```

**Comment by RX14** [comment]
@NilsIrl if you want to stream to OBS, use https://hg.sr.ht/~scoopta/wlrobs

**Comment by NilsIrl** [comment]
> @NilsIrl if you want to stream to OBS, use https://hg.sr.ht/~scoopta/wlrobs

I still have the error though.

**Comment by RX14** [comment]
@NilsIrl no... you use that instead of this, not as well as.

**Comment by soreau** [comment]
@NilsIrl 

- Install v4l2loopback kernel module
- Load the module. A new device node should appear in /dev/video*
- Run with the new device node as the file argument
- Stream with `ffplay /dev/video#`

If you get `Unknown V4L2 pixel format equivalent for rgb0` or a segfault, you might need [this patch](http://ix.io/1XQG) and to specify `-x yuv420p` with the rest of the options.

**Comment by norcalli** [comment]
@soreau why is that patch not in mainline? (or is it)

**Comment by soreau** [comment]
@norcalli No, it's not upstream. I probably could submit a PR for it.

**Comment by soreau** [comment]
@norcalli I submitted a PR for it. It just gives ability to use shorthand -m instead of --muxer or -x instead of --pixel-format.

**Pull request merged**
