### PR TITLE
Update README.md: fix typo in clone url

### PR DESCRIPTION
**Pull request by RMPR**

### CODE REVIEW

**Comment by soreau** [comment]
The url should work with or without the .git suffix. It is not required.

**Comment by ammen99** [comment]
Well I don't see any harm, although I don't see why this matters either. 

@RMPR can you elaborate why we need this?

**Comment by RMPR** [comment]
I tried without the .git and had a timeout, it may be my Internet connection though, but integrating those changes is not harmful since it's formatted like that inside the clone dialog.

2019-09-02-100204_grim

**Comment by RMPR** [comment]
When I tried without the .git I had a timeout (it may be my Internet connection though) but it's not harmful since it's the way github formats it inside the clone dialog.
2019-09-17-191932_grim

**Comment by ammen99** [comment]
I'm pretty sure this must have been a network issue on your side, but you have a point about how github formats this by default. Thanks for the PR!

**Pull request merged**
