### PR TITLE
add -O/--overwrite

### PR DESCRIPTION
**Pull request by nekopsykose**
i prefer this over echoing stuff to stdin like suggested in https://github.com/ammen99/wf-recorder/issues/174

up to you though, i don't mind if it's rejected :)

### CODE REVIEW

**Review by ammen99 — COMMENTED** [review]
Many package managers provide `-y`, maybe that would be better?

**Comment by nekopsykose** [comment]
that sounds good to me too. no preference here

**Comment by ammen99** [comment]
I'd say then make it a `-y`, let's keep to the conventions ;)

**Comment by nekopsykose** [comment]
at the time i wrote that in the middle of the night i forgot what letters of the alphabet were still available... :D

**Review by ammen99 — APPROVED** [review]
Thanks!

**Pull request merged**
