### PR TITLE
main.cpp: add --list-video-codecs option

### PR DESCRIPTION
**Pull request by adtac**

### CODE REVIEW

**Comment by adtac** [comment]
Later when support for audio codecs other than aac are added, we can change this to `--list-codecs` and print both video and audio codecs with the same command.

**Comment by ammen99** [comment]
Can we not list these codecs with the `ffmpeg` command?

**Comment by adtac** [comment]
fair enough, I didn't realise ffmpeg had such an option

feel free to merge/close

**Comment by ammen99** [comment]
Okay, thank you for the PR but as already said, this lisy is already available by ffmpeg so no need to duplicate the functionality here.

**Pull request closed without merging**
