### PR TITLE
Use VP8+Vorbis on WebM for recordings

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This is commonly supported across a wide variety of social media services and is also the default in other screen recording tools on Linux (e.g. GNOME's built-in screen recording software).

### CODE REVIEW

**Comment by ammen99** [comment]
@llyyr opinion?

**Comment by llyyr** [comment]
Seems fine to me

**Comment by Conan-Kudo** [comment]
Eyyyy, CI! It works!

**Review by ammen99 — APPROVED** [review]
LGTM

**Pull request merged**
